version: '3.8'

services:
  haskode-web-client:
    build: ./haskode-web-client
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080

  haskode-http-primary:
    build: ./haskode-http-primary
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db/haskode
      - GITHUB_CLIENT_ID=a
      - GITHUB_CLIENT_SECRET=b

  haskode-http-worker:
    build: ./haskode-http-worker
    environment:
      - HTTP_PRIMARY_URL=http://primary-server:8000
    depends_on:
      - primary-server
    ports:
      - "8081:8081"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=haskode
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      -db-data:/var/lib/postgresql/data
